import Link from "next/link";
import Navbar from "./components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				{children}
				<footer>
					<div className="text-center mt-5">
						Copyright &copy;Kelechukwu 2023
					</div>
					<div className="text-center text-green-500">
						<Link href="/about">About this project</Link>
					</div>
				</footer>
			</body>
		</html>
	);
}
