"use client";
import Link from "next/link";
import Navbar from "./components/navbar";
import DashboardNav from "./components/dashboardNav";
import "./globals.css";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { Provider } from "react-redux";
import { configureStore } from "@reduxjs/toolkit";
import { userSlice } from "./store";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	const pathname = usePathname();
	//redux store reducers
	const store = configureStore({
		reducer: {
			user: userSlice.reducer,
		},
	});
	return (
		<Provider store={store}>
			<html lang="en">
				<body className={inter.className}>
					{pathname === "/dashboard" ||
					pathname === "/requests" ||
					pathname === "/account" ||
					pathname === "/settings" ? (
						<DashboardNav />
					) : (
						<Navbar />
					)}
					{children}
					{pathname !== "/login" && (
						<footer className="items-center justify-center my-10 text-md">
							<div className="text-center">Copyright &copy;Kelechukwu 2023</div>
							<div className="text-center text-green-500">
								<Link href="/about">About this project</Link>
							</div>
						</footer>
					)}
				</body>
			</html>
		</Provider>
	);
}
